import { WordData, PlaceData } from './types';

export const wordsData: WordData[] = [
  { word: "土", strokes: 3, type: "Background" },
  { word: "山", strokes: 3, type: "Background" },
  { word: "川", strokes: 3, type: "Background" },
  { word: "干", strokes: 3, type: "Background" },
  { word: "日", strokes: 4, type: "Background" },
  { word: "月", strokes: 4, type: "Background" },
  { word: "水", strokes: 4, type: "Background" },
  { word: "火", strokes: 4, type: "Background" },
  { word: "木", strokes: 4, type: "Background" },
  { word: "井", strokes: 4, type: "Background" },
  { word: "文", strokes: 4, type: "Background" },
  { word: "丘", strokes: 5, type: "Background" },
  { word: "石", strokes: 5, type: "Background" },
  { word: "台", strokes: 5, type: "Background" },
  { word: "穴", strokes: 5, type: "Background" },
  { word: "宅", strokes: 6, type: "Background" },
  { word: "竹", strokes: 6, type: "Background" },
  { word: "寺", strokes: 6, type: "Background" },
  { word: "衣", strokes: 6, type: "Background" },
  { word: "米", strokes: 6, type: "Background" },
  { word: "字", strokes: 6, type: "Background" },
  { word: "花", strokes: 7, type: "Background" },
  { word: "床", strokes: 7, type: "Background" },
  { word: "夕", strokes: 3, type: "Background Command" },
  { word: "旦", strokes: 5, type: "Background Command" },
  { word: "早", strokes: 6, type: "Background Command" },
  { word: "夜", strokes: 8, type: "Background Command" },
  { word: "冬", strokes: 5, type: "Background Command" },
  { word: "雨", strokes: 8, type: "Background Command" },
  { word: "春", strokes: 9, type: "Background Command" },
  { word: "秋", strokes: 9, type: "Background Command" },
  { word: "風", strokes: 9, type: "Background Command" },
  { word: "夏", strokes: 10, type: "Background Command" },
  { word: "入", strokes: 2, type: "Canvas Command" },
  { word: "上", strokes: 3, type: "Canvas Command" },
  { word: "下", strokes: 3, type: "Canvas Command" },
  { word: "中", strokes: 4, type: "Canvas Command" },
  { word: "左", strokes: 5, type: "Canvas Command" },
  { word: "右", strokes: 5, type: "Canvas Command" },
  { word: "出", strokes: 5, type: "Canvas Command" },
  { word: "人", strokes: 2, type: "Object" },
  { word: "刀", strokes: 2, type: "Object" },
  { word: "巾", strokes: 3, type: "Object" },
  { word: "女", strokes: 3, type: "Object" },
  { word: "子", strokes: 3, type: "Object" },
  { word: "弓", strokes: 3, type: "Object" },
  { word: "牛", strokes: 4, type: "Object" },
  { word: "犬", strokes: 4, type: "Object" },
  { word: "云", strokes: 4, type: "Object" },
  { word: "布", strokes: 5, type: "Object" },
  { word: "皿", strokes: 5, type: "Object" },
  { word: "瓜", strokes: 5, type: "Object" },
  { word: "包", strokes: 5, type: "Object" },
  { word: "羊", strokes: 6, type: "Object" },
  { word: "虫", strokes: 6, type: "Object" },
  { word: "舟", strokes: 6, type: "Object" },
  { word: "肉", strokes: 6, type: "Object" },
  { word: "車", strokes: 7, type: "Object" },
  { word: "貝", strokes: 7, type: "Object" },
  { word: "杯", strokes: 8, type: "Object" },
  { word: "果", strokes: 8, type: "Object" },
  { word: "鳥", strokes: 11, type: "Object" },
  { word: "魚", strokes: 11, type: "Object" },
  { word: "一", strokes: 1, type: "Object Command" },
  { word: "乙", strokes: 1, type: "Object Command" },
  { word: "二", strokes: 2, type: "Object Command" },
  { word: "七", strokes: 2, type: "Object Command" },
  { word: "八", strokes: 2, type: "Object Command" },
  { word: "九", strokes: 2, type: "Object Command" },
  { word: "十", strokes: 2, type: "Object Command" },
  { word: "丁", strokes: 2, type: "Object Command" },
  { word: "力", strokes: 2, type: "Object Command" },
  { word: "三", strokes: 3, type: "Object Command" },
  { word: "大", strokes: 3, type: "Object Command" },
  { word: "小", strokes: 3, type: "Object Command" },
  { word: "叉", strokes: 3, type: "Object Command" },
  { word: "口", strokes: 3, type: "Object Command" },
  { word: "亡", strokes: 3, type: "Object Command" },
  { word: "五", strokes: 4, type: "Object Command" },
  { word: "六", strokes: 4, type: "Object Command" },
  { word: "手", strokes: 4, type: "Object Command" },
  { word: "心", strokes: 4, type: "Object Command" },
  { word: "反", strokes: 4, type: "Object Command" },
  { word: "內", strokes: 4, type: "Object Command" },
  { word: "止", strokes: 4, type: "Object Command" },
  { word: "升", strokes: 4, type: "Object Command" },
  { word: "引", strokes: 4, type: "Object Command" },
  { word: "四", strokes: 5, type: "Object Command" },
  { word: "外", strokes: 5, type: "Object Command" },
  { word: "立", strokes: 5, type: "Object Command" },
  { word: "生", strokes: 5, type: "Object Command" },
  { word: "叫", strokes: 5, type: "Object Command" },
  { word: "甲", strokes: 5, type: "Object Command" },
  { word: "丙", strokes: 5, type: "Object Command" },
  { word: "老", strokes: 6, type: "Object Command" },
  { word: "休", strokes: 6, type: "Object Command" },
  { word: "吃", strokes: 6, type: "Object Command" },
  { word: "走", strokes: 7, type: "Object Command" },
  { word: "坐", strokes: 7, type: "Object Command" },
  { word: "言", strokes: 7, type: "Object Command" }
];

export const placesData: PlaceData[] = [
  { name: "田家", links: [
      { direction: "上", target: "天空" },
      { direction: "下", target: "地底" },
      { direction: "左", target: "山岳" },
      { direction: "右", target: "大海" },
      { direction: "出", target: "山水" },
      { direction: "入", target: "宅邸" }
  ]},
  { name: "宅邸", links: [
      { direction: "出", target: "田家" }
  ]},
  { name: "山水", links: [
      { direction: "入", target: "田家" }
  ]},
  { name: "大海", links: [
      { direction: "左", target: "田家" }
  ]},
  { name: "山岳", links: [
      { direction: "右", target: "田家" }
  ]},
  { name: "地底", links: [
      { direction: "上", target: "田家" }
  ]},
  { name: "天空", links: [
      { direction: "下", target: "田家" }
  ]}
];
